server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
  token:
    access:
      expiration_time: 600000
    refresh:
      expiration_time: 1800000