server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE